### ISSUE TITLE
Live environment for installing Drauger OS broken

### ISSUE THREAD

**Issue by SenlisO** [drauger-os-development/system-installer#33]
**Using DEV ISO in Virt Manager**

When booting from ISO, and the "Install Drauger OS 7.5.1", the installer eventually presents the user with only the GUI for installing the OS.
At that point, if the user exits the installer, the user is presented with the system UI that has several features broken.  Observed broken features include: changing resolution (the change does not go into affect), logging out and shutting down.  The following message is presented when the user tries to log out.

![druagerOS logout message](https://user-images.githubusercontent.com/13087164/126920196-bc585f39-5d4b-467e-86b0-4c5112035170.png)

The shut down options is grayed out

![locked out shut down options](https://user-images.githubusercontent.com/13087164/126920646-35adde14-4633-48b7-b581-2fa4d1bb6d8a.png)

**Comment by Batcastle** [comment]
This appears to be an issue with the way Xfce Panel is launched when the installer exits. It runs and renders correctly, but some functionality is broken.

This bug can be replicated by doing the following:
```
# Kill the panel
killall xfce4-panel

# elevate to root
sudo su

# From root, re-launch the panel as yourself
su <your username here> -c xfce4-panel
```
But, when you close this command, drop root privs, and launch the panel within your standard environment as a user, it works just fine. 

An alternative to this would be running this command in the file `usr/bin/system-installer` since it remains running in the standard user's environment. Maybe explore that method?

**Comment by SenlisO** [comment]
Issue fixed and tested.
