### ISSUE TITLE
7.6 grub-install failure

### ISSUE THREAD

**Issue by iexos** [drauger-os-development/system-installer#78]
Tried normal installation with automatic partitioning of `/dev/sda` and failed.

[system-installer.log](https://github.com/drauger-os-development/system-installer/files/9154662/system-installer.log)

On a side note, the installation error reporting tool seems to be broken, it complained that it failed to connect while internet connection was clearly working.

**Comment by Batcastle** [comment]
This was fixed in #77, and is undergoing testing to be merged into `master`. Until the next ISO refresh, please install using UEFI instead of Legacy BIOS mode if possible.

It is known that Installation Reporting is broken, as the server it uploads to had a major hardware failure a few weeks ago and the infrastructure to  receive these reports has not yet been set back up.

**Comment by iexos** [comment]
@Batcastle My device has legacy BIOS only.

I used GParted for manually creating two partitions. Using `msdos` (which is MBR i suppose) with `/` as `ext4` and `/home` as `/btrfs`, the installation succeeded, but booting does not. In other distros I would expect a `/boot` partition that I could not select in the installer (only `/boot/efi`). I am a bit lost.

**Comment by Batcastle** [comment]
This issue is verified as fixed. Closing issue.
